import FormulaButton from "../components/FormulaButton";

function SetAndProp({input, handleInputUpdate}) {
    return (
        <div className="ButtonsContainer">
            <span className="FormulaButtonsContainer">
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\in'} 
                    imgUrl={'\\in'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\ni'} 
                    imgUrl={'\\ni'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\notin'} 
                    imgUrl={'\\notin'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\not\\ni'} 
                    imgUrl={'\\not\\ni'}
                />
            </span>
            <span className="FormulaButtonsContainer">
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\subset'} 
                    imgUrl={'\\subset'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\supset'} 
                    imgUrl={'\\supset'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\subseteq'} 
                    imgUrl={'\\subseteq'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\supseteq'} 
                    imgUrl={'\\supseteq'}
                />
            </span>
            <span className="FormulaButtonsContainer">
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\not\\subset'} 
                    imgUrl={'\\not\\subset'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\not\\supset'} 
                    imgUrl={'\\not\\supset'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nsubseteq'} 
                    imgUrl={'\\nsubseteq'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nsupseteq'} 
                    imgUrl={'\\nsupseteq'}
                />
            </span>
            <span className="FormulaButtonsContainer">
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\cap'} 
                    imgUrl={'\\cap'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\cup'} 
                    imgUrl={'\\cup'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\varnothing'} 
                    imgUrl={'\\varnothing'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\left\\{ \\right\\}'} 
                    imgUrl={'\\left\\{a\\right\\}'}
                />
            </span>
            <span className="FormulaButtonsContainer">
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\Rightarrow'} 
                    imgUrl={'\\Rightarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\Leftarrow'} 
                    imgUrl={'\\Leftarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nRightarrow'} 
                    imgUrl={'\\nRightarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nLeftarrow'} 
                    imgUrl={'\\nLeftarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\Leftrightarrow'} 
                    imgUrl={'\\Leftrightarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nLeftrightarrow'} 
                    imgUrl={'\\nLeftrightarrow'}
                />
            </span>
            <span className="FormulaButtonsContainer">
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\rightarrow'} 
                    imgUrl={'\\rightarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\leftarrow'} 
                    imgUrl={'\\leftarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nrightarrow'} 
                    imgUrl={'\\nrightarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nleftarrow'} 
                    imgUrl={'\\nleftarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\leftrightarrow'} 
                    imgUrl={'\\leftrightarrow'}
                />
                <FormulaButton
                    input={input}
                    handleInputUpdate={handleInputUpdate} 
                    inputOp={'\\nleftrightarrow'} 
                    imgUrl={'\\nleftrightarrow'}
                />
            </span>
        </div>
    );
}
export default SetAndProp;